#!/usr/bin/env python3
"""Generate include/build_info.h with the current git commit / branch /
build timestamp, so the firmware can advertise its version through
/api/version and the chat UI can warn the user when the browser is
running stale cached HTML.

This script is idempotent: it does NOT rewrite the header if all three
fields would be unchanged, so PlatformIO's incremental build doesn't
recompile every dependent translation unit on every `pio run`.

Usage:
    python3 scripts/gen_build_info.py
"""
import datetime
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "include", "build_info.h")

def git(*args, fallback=""):
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, *args],
            check=True, capture_output=True, text=True,
        )
        return out.stdout.strip()
    except Exception:
        return fallback

def main():
    commit_full = git("rev-parse", "HEAD", fallback="unknown")
    commit      = commit_full[:12]
    branch      = git("rev-parse", "--abbrev-ref", "HEAD", fallback="unknown")
    # Mark "dirty" if there are uncommitted changes (excluding the
    # generated header itself and the embedded UI header, which both
    # change every build).
    dirty = git("status", "--porcelain", "--untracked-files=no",
                ":(exclude)include/build_info.h",
                ":(exclude)include/embedded_ui.h",
                fallback="")
    if dirty:
        commit += "-dirty"
    build_time  = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    body = (
        "// Auto-generated by scripts/gen_build_info.py — do not edit.\n"
        "#pragma once\n"
        f'#define BUILD_COMMIT "{commit}"\n'
        f'#define BUILD_COMMIT_FULL "{commit_full}"\n'
        f'#define BUILD_BRANCH "{branch}"\n'
        f'#define BUILD_TIME   "{build_time}"\n'
    )

    # Skip rewriting if commit + branch haven't changed.  The build
    # time always advances, so we only refresh when something else
    # changed — keeps incremental builds fast.
    if os.path.isfile(OUT):
        with open(OUT) as f:
            existing = f.read()
        if (f'#define BUILD_COMMIT "{commit}"' in existing and
            f'#define BUILD_BRANCH "{branch}"'  in existing):
            print(f"[build_info] unchanged ({commit} @ {branch})")
            return

    with open(OUT, "w") as f:
        f.write(body)
    print(f"[build_info] wrote {commit} @ {branch} ({build_time})")

if __name__ == "__main__":
    main()
