// Auto-generated by scripts/gen_build_info.py — do not edit.
#pragma once
#define BUILD_COMMIT "0578ae964afd-dirty"
#define BUILD_COMMIT_FULL "0578ae964afda5cb3009c9f41130ce5c45b1940d"
#define BUILD_BRANCH "master"
#define BUILD_TIME   "2026-05-11T10:05:21Z"
