// Auto-generated by scripts/gen_build_info.py — do not edit.
#pragma once
#define BUILD_COMMIT "230ff5028059-dirty"
#define BUILD_COMMIT_FULL "230ff5028059ae2ee32d29ea096cae73cb559217"
#define BUILD_BRANCH "master"
#define BUILD_TIME   "2026-05-11T15:52:50Z"
