// Auto-generated by scripts/gen_build_info.py — do not edit.
#pragma once
#define BUILD_COMMIT "bc7d57d6f8e0-dirty"
#define BUILD_COMMIT_FULL "bc7d57d6f8e0a1fbc7fa4f67bfc169dd33d84c17"
#define BUILD_BRANCH "master"
#define BUILD_TIME   "2026-05-11T12:38:20Z"
